### ISSUE TITLE
Client side: Use LESS!!

### ISSUE THREAD

**Issue by o5** [o5/grido#121]

**Comment by MartyIX** [comment]
You can use http://css2less.cc/ for a simple transformation of your CSS to LESS. :)

**Comment by jkuchar** [comment]
@MartyIX Thanks for tip! This sounds great!

**Comment by o5** [comment]
It's not only about convert <code>css</code> => <code>less</code>. There should be exists some task runner because I don't want to change both <code>grido.less</code> and <code>grido.css</code> file. With task runner, I can also build <code>*.js</code> files like <code>grido.min.js</code> or even <code>grido.bundle.js</code>. 

Big question for me is: SASS or LESS? I currently prefer sass but someone prefers less. With supporting of both will not easy to maintenance.

**Comment by jelen07** [comment]
:+1: for SASS due upcoming Bootstrap 4.

**Comment by Lexinek** [comment]
From my perspective, i use LESS only, but as @jelen07 mentioned, when BS4 arrives, i will switch to SASS
