### ISSUE TITLE
Is validation of page number necessary on production mode?

### ISSUE THREAD

**Issue by bohacf** [o5/grido#176]
Hi,
I get "PHP User Notice: Page is out of range." error message. In Debug mode is expectable, but in production debugger generates error, send me mail and create log/email-send file :(

Frantisek

**Comment by o5** [comment]
Yes, this behaviour is also here [1](https://github.com/o5/grido/blob/2396cfb17b46eff4cb35fc5c912be77291d68df1/src/Grid.php#L806), [2](https://github.com/o5/grido/blob/2396cfb17b46eff4cb35fc5c912be77291d68df1/src/Grid.php#L823-L842), [3](https://github.com/o5/grido/blob/2396cfb17b46eff4cb35fc5c912be77291d68df1/src/Grid.php#L862), [4] (https://github.com/o5/grido/blob/2396cfb17b46eff4cb35fc5c912be77291d68df1/src/Components/Operation.php#L118), but I don't know, what should be better. I think, add condition for production mode is ugly. Is better to throw <code>\Nette\Application\BadRequestException</code>? I don't think so.

**Comment by bohacf** [comment]
and what about this:

if (\Tracy\Debugger::$strictMode === TRUE) { 
    trigger_error("Page is out of range.", E_USER_NOTICE);
} 

?

**Comment by o5** [comment]
I think, this is same as condition for production mode :/

**Comment by bohacf** [comment]
ok, workaround is:

class MyGrid extends \Grido\Grid {
    public function render() {
        error_reporting(E_ALL & ~E_USER_NOTICE);
        parent::render();
        error_reporting(E_ALL);
    }
}
