### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by TomasVotruba** [o5/grido#177]
I see you've added few [assets](https://github.com/o5/grido/commit/76efc7229f63d1ae2aa9078bcbbcd8f1e8dadc40) to the package.
We use them in our project, but when I tried to change the @dev tag to some stable, I saw these files were not available yet.

Could you please tag new version to include them? Thank you

**Comment by o5** [comment]
I know about this and I'm sorry for troubles. You should use @dev version, where the assets should be located or use bower package with link to a specific commit ([example in sandbox](https://github.com/o5/grido-sandbox/blob/master/bower.json#L14). 

Currently state is not ready for tag a new version.

**Comment by TomasVotruba** [comment]
@o5 Just installed bower and the link did the trick, thank you.
