### ISSUE TITLE
DateRangeFilter with empty string causes error

### ISSUE THREAD

**Issue by sasule** [o5/grido#178]
I would like to report probably bug in DateRangeFilter (DateFilter is ok with same order of operation).
I have this order of operations:
1) I choose date range, then search  - that's ok
2) then I go into the filter field and delete entered value and make a search.

Operation (2) causes error "Column count must be odd". 

My guess is the problem lies in here https://github.com/o5/grido/blob/master/src/Components/Filters/DateRange.php#L108-L110, in calling setupEmpty method, respectively. I hope, returning NULL would solve the problem. 

Anyway if my opinion is right, I can make a pull request.

Saša

**Comment by o5** [comment]
I can't reproduce :/

![test](https://cloud.githubusercontent.com/assets/218562/6426860/47fcd4e6-bf6e-11e4-9425-e42dd61cb01b.gif)

**Comment by o5** [comment]
@sasule je to stále aktuální?

**Comment by sasule** [comment]
Nevím, ověřím. Tam, kde mi to padalo, jsem si udělal fix.
Teď koukám, že jsem nenapsal důležitou informaci, že to bylo na Doctrine a Postgre.
Saša

**Comment by sasule** [comment]
Tak bohužel, stále zlobí.
Moje konfigurace je momentálně Grido 2.0.8 + Nette 2.3.0 + PHP 5.6.5
DateRangePlugin mám ve verzi 1.3.7 (což je poněkud neaktuální, ale to by snad vadit nemělo).

Saša

**Comment by o5** [comment]
@sasule můžeš to pls zkusit s aktuálním grido-examples (<code>composer create-project o5/grido-examples</code>) s [tímto](https://gist.github.com/o5/72f0de6ee94763e76011) doctrine presenterem? nebude tam nalinkovaný daterange plugin, takže filtruj třeba s **29.09.1996 - 31.12.1996**?

Mně to totiž jde i s doctrínou, jediný v čem se to lyší je postgres.

**Comment by sasule** [comment]
Tak s tím, co jsi poslal, to je OK. 
DRPicker jsem si přilinkoval, vše jde bez problémů. Pokud rozsah není vyplněn, tak zmizí i z URL, tož to :+1: 
Saša

**Comment by cubic** [comment]
Můžu poprosit o info, jak tohle vyřešit? Ten odkazovaný presenter už neexistuje. Řeším ten samý problém na Doctrine / MySQL. Díky moc.

**Comment by o5** [comment]
@cubic pokud si vzpominam, tak tam nebylo nic specialniho, jen nahrazeni `setFilterDate()` => `setFilterDateRange()`

**Comment by cubic** [comment]
@o5 To právě mám. Jde o to, že klient má přehled objednávek, kde si je filtruje podle data. Zadá rozmezí datumů, klikne na filter, podívá se... Pak ručně odmaže obsah filtru, potvrdí filtr a vyhodí to InvalidArgumentException('Count of column must be odd.') z Condition.php ř. 67. Koukal jsem na to jen v rychlosti, ale hodnota $column jako parametr setColumn() je prázdné pole. Takže nevím, jestli je to bug a nebo dělám něco blbě já.

**Comment by sasule** [comment]
@cubic Pokud Ti to stále zlobí, navrhuji na sloupec navěsit vlastní setWhere() callback, kde si ohlídáš, zda je to prázdný řetězec, já to řeším s Doctrinou takto:

```php
 public static function searchDateGrido($value, \Kdyby\Doctrine\QueryBuilder $queryBuilder, $column)
    {
        try {
            $dt = new \Nette\Utils\DateTime($value);
        } catch (\Exception $e) {
            return "";
        }
        $end = clone $dt;
        $end->modify('+1day');

        $queryBuilder->andWhere(sprintf('%s >= :start AND %s < :end', $column, $column))
            ->setParameter('start', $dt)
            ->setParameter('end', $end);
    }

...

        $ic = $grid->addColumnDate('invoiceCreated', "faktura vytvořena", \Grido\Components\Columns\Date::FORMAT_DATE);

            $ic->setSortable()
                ->setFilterDate()
                ->setWhere(function ($value, $qb) {
                    Sasule\Utility::searchDateGrido($value, $qb, 't.invoiceCreated');
                });
```

**Comment by cubic** [comment]
@o5 Díky moc, ráno zkusím.

**Comment by MartinSzollos** [comment]
Chtěl bych nahlásit, že tento problém stále trvá, vyzkoušeno na novém o5/grido-examples, při zapnutí 
$grid->setRememberState()
