### ISSUE TITLE
Entities require magic accessors by property accessor

### ISSUE THREAD

**Issue by TomasVotruba** [o5/grido#179]
Use case:

**Entity.php**

```php
class Entity
{

   /**
    * @var int 
    */
   private $id;

   /**
    * @return int
    */
   public function getId()
   {
       return $this->id;
   }

}
```

When grido tries to get property like this: https://github.com/o5/grido/blob/bf8659cd63607203df704c9344195c22878daf04/src/PropertyAccessors/ArrayObjectAccessor.php#L51, it fails on missing property.

It probably requires `Nette\Object` magic accessor. 

**Possible fix:** add getter call if exists

---

Is `ArrayObjectAccessor` somehow incompatible with Symfony PropertyAccessor? Or what the reason to prefer it?

**Comment by o5** [comment]
@pepakriz: Could you look at this?

**Comment by pepakriz** [comment]
`ArrayObjectAsseccor` is only light and naive implementation of `IPropertyAsseccor` which work only with array or object with property access. If you need more complex solution, use SymfonyPropertyAccessor. It is depend on `symfony/property-access` of course.

**Comment by TomasVotruba** [comment]
@pepakriz I see, but what's the advantage?  So it's corrrect behavior to enforce public properties?

**Comment by TomasVotruba** [comment]
Ping @pepakriz

**Comment by pepakriz** [comment]
@TomasVotruba Asi přesně nerozumím, co máš za problém? Chceš, aby `ArrayObjectAsseccor` podporoval volání getterů? Ve svých projektech využívám všude symfony accessor, protože umí i další featury, například tečkovou notaci znamenající zanoření,...

Že není symfony accessor výchozí bude pravděpodobně kvůli závislosti, která by možná mohla někomu vadit, nevím. Mě osobně by to nevadilo. @o5

**Comment by TomasVotruba** [comment]
@pepakriz  Viz use case v prvním příspěvku.

1. `getProperty` na `ArrayObjectAccessor` zavolá `return $object->$name;`
2. To se pokusí zavolat `$object->id` (kde `$object` je instance mé třídy `Entity`)
3. To skončí chybou, protože `$id` je private a k dispozici je pouze metoda `getId()`

To je v OOP pro mě nečekané chování.

Také využívám Symfony PropertyAccess, proto mě překvapuje, že je tu nějaké custom nefční řešení.
Osobně preferuji fční řešení, tím spíše, když je v `suggest` sekci - s touto chybou se tedy už někdo nejspíše setkal.

Pokud odsouhlasíte (nevím jak to tu máte) Symfony\PropertyAccess, rád pošlu PR.

**Comment by pepakriz** [comment]
No podle mě se to právě chová korektně. Ten accessor prostě umí pracovat pouze s polem nebo s objektem, který umí property access, což tvá entita nesplňuje. Jako jo, asi by se ta podpora pro gettery mohla dopsat, ale proč, když je tu symfony accessor.

Momentálně mě nenapadá, v čem by mohl nastat problém, kdyby se ArrayObjectAccessor nahradil za symfoňáckej, takže jsem pro PR. Ale hlavní slovo má samozřejmě @o5

**Comment by TomasVotruba** [comment]
Ping @o5

**Comment by o5** [comment]
@TomasVotruba co tedy navrhuješ? Zrušit celé <code>src/PropertyAccessors</code> a použít Symfony\PropertyAccess? Pokud s tím budou fungovat všechny datasources, tak asi proč ne.

**Comment by TomasVotruba** [comment]
@o5 Přesně tak! Od toho jsou testy. Pošlu PR?

**Comment by o5** [comment]
@TomasVotruba sobota jsem byl kompletně off a včera jsem to v rychlosti zkusil a testy právě neprošly. Takže tomu bude třeba dát trochu péče.

**Comment by o5** [comment]
> Momentálně mě nenapadá, v čem by mohl nastat problém, kdyby se ArrayObjectAccessor nahradil za symfoňáckej, takže jsem pro PR

Mě taky nic nenapadlo, než jsem zkusil aktuální Grido (pouze se symfonním accessorem) na projektu kde používám NetteDatabase. V jednom use-casu totiž končím na [této výjimce](https://github.com/symfony/PropertyAccess/blob/7c3a33ba466a61bfdbca7d89118f99cf25a588c1/PropertyAccessor.php#L182). Jde o situaci, kdy cizí klíč je <code>NULL</code> - to databáze pro test nyní neobsahuje a proto to prošlo.

[Udělal](https://github.com/o5/grido/commit/e3eadfd2d51427db0591df631a607ec4ae123ebb) jsem novou větev a [tady](https://travis-ci.org/o5/grido/jobs/53506413#L363) je ukázka toho, kde to failuje. Asi budu muset ten původní ArrayAccessor vrátit, přemýšlím zda-li ho nechat i jako výchozí či nikoli.

Failuje tam i doctriní test, protože jsem nedokázal přijít na to, jak donutit aby místo <code>INNER JOIN</code> udělala <code>LEFT</code> či <code>RIGHT</code>. Nevíte pls?

**Comment by TomasVotruba** [comment]
Stačí [sem](https://github.com/o5/grido/blob/42da82d953e58492d2229ab754e90e57a79cfc85/src/PropertyAccessors/SymfonyPropertyAccessor.php#L40) přidat [kontrolu typu](https://github.com/symfony/PropertyAccess/blob/7c3a33ba466a61bfdbca7d89118f99cf25a588c1/PropertyAccessor.php#L181) a vrátit `NULL`, pokud neprojde.

**Comment by o5** [comment]
To nepomůže. Když si stáhneš tu upravenou db, tak tímhle se to nechá debugovat.
```php
$object = $this->database->table('user')->where('id = ?', 1)->fetch();
$accessor = new \Symfony\Component\PropertyAccess\PropertyAccessor();
dump($accessor->getValue($object, 'country.title'));exit(1); //vrací správně Iceland

$object = $this->database->table('user')->where('id = ?', 39)->fetch();
$accessor = new \Symfony\Component\PropertyAccess\PropertyAccessor();
dump($accessor->getValue($object, 'country.title'));exit(1); //Expected argument of type "object or array", "NULL" given
```

**Comment by o5** [comment]
> Failuje tam i doctriní test, protože jsem nedokázal přijít na to, jak donutit doctrinu, aby místo <code>INNER JOIN</code> udělala <code>LEFT</code> či <code>RIGHT</code>. Nevíte pls?

Bude to asi nějaká blbost v [definici entity](https://github.com/o5/grido/blob/accessor-and-nullable/tests/DataSources/files/doctrine/entities/User.php#L63-L68). Tím <code>INNER JOIN</code> se zahodí celý řádek, ale já chci zobrazit prázdnou hodnotu, takže bych potřeboval <code>LEFT JOIN</code>. Jak se to v doctrine dělá? Dík :) cc @pepakriz

**Comment by TomasVotruba** [comment]
Resime acesor nebo db? Ztracim se v tom.

Mas link na test, kde muj posledni navrh failuje?

**Comment by o5** [comment]
Resime accessor a NetteDatabase. [Tento](https://github.com/o5/grido/commit/e3eadfd2d51427db0591df631a607ec4ae123ebb#diff-e8a0740e4690f26f30e6bb65215843fdR94) test by měl procházet.

**Comment by TomasVotruba** [comment]
Nikde tam nevidím, [co píšu tady](https://github.com/o5/grido/issues/179#issuecomment-77739981).

**Comment by o5** [comment]
To tam není, ale jak jsem zkoušel ráno, problém to neřeší.

**Comment by TomasVotruba** [comment]
Pokud mi dáš failující test s tím kódem, můžu ho opravit.

**Comment by o5** [comment]
Je v [accessor-and-nullable](https://github.com/o5/grido/tree/accessor-and-nullable) větvi.

**Comment by TomasVotruba** [comment]
Simple https://github.com/o5/grido/pull/187
