### ISSUE TITLE
JavaScript: refresh method

### ISSUE THREAD

**Issue by garncarz** [o5/grido#185]
Is there some clean API way to ask Grido to reload its data? So far, I've been using the function below which worked quite well (until the first failed response from server), but it was polluting browser's history (and I didn't find its way very neat). Anyway, it doesn't work now (after an upgrade done after several months).

```js
function gridoRefreshing(gridoName, interval) {
	if (typeof(interval) === "undefined") {
		interval = 60;
	}	
	
	var refreshParam = "&" + gridoName + "-refresh";
	
	setInterval(function() {
		if (window.location.hash.indexOf(refreshParam) >= 0) {
			return;
		}
		window.location.hash += refreshParam;
	}, interval * 1000);
}
```

**Comment by garncarz** [comment]
Maybe it doesn't work now because of troubling `jquery.ba-hashchange.min.js`, but still, some API call would be nice.

**Comment by o5** [comment]
Hi, ajax hashchange and <code>jquery.ba-hashchange.min.js</code> has been removed with [commit](https://github.com/o5/grido/commit/2c288f659732c60187e9e1b9837940bf264dc008). You can look at [the demo](https://github.com/o5/grido-examples), which uses a new way.
