### ISSUE TITLE
Allow display operation checkbox

### ISSUE THREAD

**Issue by f3l1x** [o5/grido#190]
Allow display row checkbox wihout operations. I wanna handle ID's my own. But now I have to write this and remove operation select from template.

```php
// Display row checkboxes
$this->setOperation(['run'], function ($operation, $ids) {});
```

I suggest `$grid->setShowOperationCheckbox(TRUE)` or something like that.

**Comment by o5** [comment]
I don't understand, what do you want. Can you explain more your use case?

**Comment by f3l1x** [comment]
I extended grido layout and added my own form. I need to display checkbox for every row. There's already some checkbox, but is shown only with sem operations.

I would like to show these checkboxes manual.

**Comment by o5** [comment]
Sorry, this feature request does not make sense for me.
