### ISSUE TITLE
How to disable perPageList?

### ISSUE THREAD

**Issue by TomasVotruba** [o5/grido#191]
I don't want to bother user by this feature. IMO should be optional, not enforced.
I didn't find any options for this, but maybe I was looking wrong.

If there's no option to disable this, would you be open to PR?

**Comment by o5** [comment]
Currently, there is no way to disable it and I think that existence is pointless. Same as feature for disable pagination because both are the basic feature (for me). 

You can hide by CSS:
```css
.grido .count select {
    display: none;
}
```

**Comment by TomasVotruba** [comment]
I'd prefer user to choose features and not enforce it. Would you be open to PR? 

IMO hiding PHP features by CSS is bit overkill.
