### ISSUE TITLE
Render problem: inconsistency of glyphicon and FontAwesome (fa-stats)

### ISSUE THREAD

**Issue by bohacf** [o5/grido#193]
HTML is not displayed correctly - icon fa-stats not exists!
```
$stats = $grid->addActionHref('customStats', '')->setIcon('stats');

html output:
<i class="glyphicon glyphicon-stats fa fa-stats icon-stats"></i> 
```

**Comment by bohacf** [comment]
info-sign has problem too; quick jQuery workaround (must be also executed after redraw grid with ajax):
```
$("i.icon-stats, i.icon-info-sign").each(function() {
   $(this).removeClass('fa');
   $(this).removeClass('fa-stats');
   $(this).removeClass('fa-info-sign');
});
```

**Comment by o5** [comment]
This is not a bug. <code>setIcon()</code> is the shortcut if you use [Glyphicon](http://glyphicons.com/) or [Font Awesome](http://fortawesome.github.io/Font-Awesome/icons/). If not, use 
```php
$grid->addActionHref('customStats', '')->elementPrototype->class[] = 'stats';
```
