### ISSUE TITLE
Invalid $.get URL for refresh, when grid is subcomponent of a component

### ISSUE THREAD

**Issue by Lexinek** [o5/grido#194]
I am using grid as component wrapped by component. For example i have TestGrid component in presenter, and this component has grid component inside of it.

[On this line](https://github.com/o5/grido/blob/master/client-side/js/grido.js#L490) there is code, which is causing the AJAX request. But the ajax request contains wrong component name (only of the grid component, does not include the parent component name)

The request url looks like **xyz&do=grid-refresh&_=1427454251445** but it should be **xyz&do=testGrid-grid-refresh&_=1427454251445**

Afterwards 500 occurs:
*Nette\Application\UI\BadSignalException #403
The signal receiver component 'grid' is not found.*

**Comment by Lexinek** [comment]
Im already preparing pull request for this one with working fix.

**Comment by o5** [comment]
Ok, I'm waiting :)
