### ISSUE TITLE
Export to CSV didnt return all lines.

### ISSUE THREAD

**Issue by keeper7** [o5/grido#198]
During CSV export not all lines are returned. In my test only about 1/3 of lines are returned.
When I comment line 111 in Export.php

`$httpResponse->setHeader('Content-Length', mb_strlen($source, $encoding));`

everything work fine.
Possible fix:

`$httpResponse->setHeader('Content-Length', strlen($source));`

**Comment by janfiedler** [comment]
I have same problem export was only  1881 row and cut in half. With your suggestion possible fix is working for me and get complete 3760 row in export.
Thank you

**Comment by o5** [comment]
Closed via https://github.com/o5/grido/commit/59f37b243f6655fcf70ae8b7bf08d286c63c81ec.
