### ISSUE TITLE
Export makes too many queries

### ISSUE THREAD

**Issue by mzstic** [o5/grido#206]
There was a fix earlier https://github.com/o5/grido/commit/a0990cb28fe30612758fc19add4e858b79751315#diff-24b1fbceb993113241f3418dd35590c5R46
important is src/Components/Export.php:44
But for me it is only causing problems. I'm using Nette Database. In total I have 60 000 rows (and will need more...) And with this magical constant *$limit = 100* export makes 600 requests, which takes too much time.

When I set no limit (it means $limit = 100000) execution time is cca 24 seconds
$limit = 10000 -> 28 seconds
$limit = 1000 -> 1.8 minutes
$limit = 100 -> runs forever...

Is there any reason this constant is set to 100 and cannot be changed anyhow?

**Comment by o5** [comment]
Closed via https://github.com/o5/grido/commit/59f37b243f6655fcf70ae8b7bf08d286c63c81ec.
