### ISSUE TITLE
Inline edit problem

### ISSUE THREAD

**Issue by vojtys** [o5/grido#210]
Hi, when I use methods `setEditableControl` and `setEditableCallback` on some column, table is rendered without identifier `id="controlName"`, than paging with history.js doesnt work correctly.

When I use `setEditableColumns` method on grid. Inline editing is not work.

I am using `@dev` version
Thx

**Comment by Ciki** [comment]
I second that..

the reason is Editable calls getTablePrototype on grid while [grid's name is still `NULL`](https://github.com/o5/grido/blob/4b03630883a88c1711c95d3943a739392f81cf79/src/Grid.php#L506)

**Comment by vojtys** [comment]
Thanks! I am doing it wrong...

**Comment by o5** [comment]
It should be fixed via https://github.com/o5/grido/commit/0ff229d9882e7841bbacb0dc18dd6680d752e63e.
