### ISSUE TITLE
Humanized boolean values

### ISSUE THREAD

**Issue by TomasPilaru** [o5/grido#216]
Hi,
i used Grido for manage articles in CMS. I have column `published` in article table which has a boolean type. If i add this column to Grido using `$grido->addColumnText()`, (because there isn't method e.g. `addColumnCheck()` but filter exists (`setFilterCheck()`) in the rendered table are boolean values implicit type cast to string so i see values like 1 or 0... These values are not human readable.
I think it would be good to add a new column type check and render boolean values as yes or no.

**Comment by o5** [comment]
Sorry, [there](https://github.com/o5/grido/issues/127#issuecomment-41602197) was similar feature request.
