### ISSUE TITLE
Show/hide columns for export/display

### ISSUE THREAD

**Issue by Olicek** [o5/grido#232]
Hi,
has Grido something for showing/hiding columns? I need display some columns at display and use some additional columns for export. Can i do it somehow? [I have prepared event](https://forum.nette.org/cs/13109-grido-datagrid-pro-nette?p=18#p160738) for that, but if Grido can do it natively, it would be better.

But i will need another one feature: Show customized columns for every user. I know, i can wrap the column into some if block, but better would be something like this:

```
$grido->disabledColumns(array('street', 'number', 'zip'));
```

Has it something for that? Or can i prepare PR?

**Comment by o5** [comment]
> and use some additional columns for export. Can i do it somehow?

In version **2.1.0** you [can use the $export->setCustomData()](https://github.com/o5/grido/commit/fffb42ccd4eeb0f825ee528190261c86776f918f#diff-2b3389ee75761d52bf54a074e6f2263aR139) to do it.

And your feature request should be resolved with this piece of code. (Standard Nette's way)
```php
$disabledColumns = ['street', 'number', 'zip'];
foreach ($disabledColumns as $colum) {
     $grid[\Grido\Components\Columns\Column::ID]->removeComponent($grid->getColumn($colum));
}
```
