### ISSUE TITLE
Nefungující JS v tabulce při použití metody Ajax

### ISSUE THREAD

**Issue by misaon** [o5/grido#233]
Ahoj, díky moc, za tento super skript. Mám ale pár malých potíží..

Když v tabulce používám nějaké JS prvky (např. Bootstrap tooltip), tak po výběru libovolného Grido filtru přestanou fungovat. Musím zdůraznit, že se to stane jen pokud využívám v Gridu ajax. Když chci třeba místo FilterSelect použít externí JS plugin select2, opět při aktivaci libovolného filtru plugin select2 přestane fungovat. Tyto pluginy se dají využívat jedině, když mám v Grido ajax vypnutý a stránka provede refresh, potom vše funguje tak jak má. 
Existuje nějaký způsob, jak při zapnutém ajaxu zachovat funkčnost externích JS pluginů?

Ten samý problém nastává i když místo checkboxů (setOperation) použiji JS plugin iCheck. Výběr takovýchto položek není možný, protože jej Grido nerozpozná, je to škoda.

Díky a za reakci a mnoho úspěchů, budu tvým stálým fandou :)

**Comment by sasule** [comment]
Ahoj, 
u externích pluginů typu select2, tooltipy, popovery apod. je potřeba zavolat jejich inicializace při každé inicializaci gridu.
Cesty jsou 2:
1) napíšeš si Grido plugin, kde v inicializaci zavoláš inicializaci toho, co potřebuješ. Fungovat to bude, sám používám např. pro select2

2) napíšeš si rozšíření pro nette.ajax, které bude reagovat na "complete" událost (?? - nevím, zda událost je správné slovo), kde zase uděláš inicializaci těch prvků,c o potřebuješ.

**Comment by misaon** [comment]
Díky moc za rychlou odpověď. Mohl by si prosimtě ukázat, jak to máš? Sám se s tím delší dobu trápím.
Díky

**Comment by sasule** [comment]
Zde je kód pro select2 (select2 verze 4.0 - poslední) a Grido je také poslední.
```
;
(function ($, window, undefined) {
    /*jshint laxbreak: true, expr: true */
    "use strict";

    window.Grido.Grid.prototype.onInit.push(function (Grido) {
        if ($.fn.select2 === undefined) {
            console.error('Plugin "select2" is missing!');
        } else {

            var $el = $('th select', Grido.$element);

            $(".select2-container.select2-container--default.select2-container--open").remove();

            $el.each(function () {
                var $sel = $(this);
                if (!$sel.hasClass("no-select-2")) {
                    $sel.select2({
                        allowClear: true,
                        dropdownAutoWidth: true,
                        placeholder: $sel.data('placeholder') === undefined ? '' : $sel.data('placeholder')
                    });
                }
            });
        }
    });

})(jQuery, window);
```

**Comment by misaon** [comment]
Super, díky moc, počítám, že tímhle si rozšířil nette.ajax že?

**Comment by sasule** [comment]
Ne, vůbec ne. Tohle stačí uložit do souboru .js a nalinkovat do stránky po nalinkování grida. Podívej se na nejnovější grido + sandbox.
Tam to je všechno uděláno :-)

**Comment by misaon** [comment]
Moc si mi pomohl, zaplať pán bůh za tebe :)

Teď ještě nějak zázračně vyřešit ten iCheck plugin a budu chrochtat blahem :D ...
