### ISSUE TITLE
No sorting, filter etc. when URL include same parameter

### ISSUE THREAD

**Issue by misaon** [o5/grido#241]
Ahoj, mám problém,

když v Nette zavolám nějakou akci, v její šabloně mám includované GRIDO, a v url mám nějaký parametr, například:
**http://localhost/INTRANET/invoices/items?project_id=6**

Parametr project_id udává ID projektu, které mám následně interpretováno v presenteru následovně:
$grid->model = $this->database->table('invoices_items')->where('project_id = ?', **$this->getHttpRequest()->getQuery('project_id')**);

Jenže když nyní dám seřadit jakýkoliv sloupec v tabulce, ajaxový požadavek se provede, ale ke změně řazení sloupců nedojde, do url se nepřidají parametry 
**?gridProjects-sort[created_by]=asc&gridProjects-sort[customer_id]=asc**

Takže řazení nefunguje. Potřebuju skrz parametr v URL ovládat výběr záznamů z databáze a jiný způsob než tenhle mě nenapadá.. Dá se to nějak řešit?

**Comment by o5** [comment]
Udelej z parametru `project_id` persistentni parametr a bude ti to fungovat.

**Comment by misaon** [comment]
Neskutečný, moje blbost ale otevřel si mi oči, díky a doufám že s vývojem neskončíš, nevím co jiného bych používal! :)
