### ISSUE TITLE
how to reload data after operation processed

### ISSUE THREAD

**Issue by Ciki** [o5/grido#242]
```php
$grid->setOperation([
				'refresh' => 'Prepočítať',
				], function($operation, array $ids) use($grid) {
				if ($operation === 'refresh') {
					$this->refreshEstate($ids);
                                }
                                // how do I reload grid data here?
});
```

**Comment by o5** [comment]
I'm using a classical call `$presenter->redirect('this')`

**Comment by Ciki** [comment]
Is it possible to reload grid for ajax requests?

**Comment by o5** [comment]
What about `$grid->reload()`?

**Comment by Ciki** [comment]
I tried to no avail..

**Comment by o5** [comment]
I just tried in [grido-examples](https://github.com/o5/grido-examples/blob/aca7d4d38dc315a8a8157ed040a3946605790af2/app/presenters/Presenter.php#L34-L35). I added call to data change before linked lines and it works as expected.

**Comment by Ciki** [comment]
with which presenter did you test it? It does not work for me, can you please post your changes so I can test it as well?
Thanks

**Comment by Ciki** [comment]
it could be solved by adding `$this->data = NULL;` before [this line](https://github.com/o5/grido/blob/master/src/Grid.php#L785)
so when getData() is called after operation processed the data is not fetched from cache
what you think?

**Comment by o5** [comment]
@Ciki: You had right, sorry! Could you test it now?

BTW: With this [change](https://github.com/o5/grido/commit/56fa54d266b3982079df53b1838d16f2c1c26836) you can omit call `$grid->reload()` in our operation handler.

**Comment by Ciki** [comment]
uff I finally tracked the bug down after an hour .. please beware of this [condition](https://github.com/o5/grido/blob/master/src/Grid.php#L464-L466)
if the getData() is first called using cache the result is stored in `$this->data`. Then within operation handler is fetched new data but not stored in `$this->data` as `$useCache=false` thus any subsequent calls to `getData()` using cache will return original(outdated) data

**Comment by o5** [comment]
I tested it yesterday with this modification (and latest dev version of  Grido) and it worked fine.

[grido-examples/Presenter.php](https://github.com/o5/grido-examples/blob/master/app/presenters/Presenter.php#L24-L39)
```php
public function handleOperations($operation, $ids)
{
    if ($ids) {
        $row = implode(', ', $ids);
        $this->flashMessage("Process operation '$operation' for row with id: $row...", 'info');
    } else {
        $this->flashMessage('No rows selected.', 'error');
    }

    // LITTLE MODIFICATION
    foreach ($ids as $id) {
        $this->context->getByType('\Nette\Database\Context')
            ->table('user')
            ->where('id', $id)
            ->delete();
    }

    $this->redrawControl('flashes');
}
```

**Comment by Ciki** [comment]
seems like it's working now in my project.. hopefully it'll stay this way :) Thanks!

**Comment by Ciki** [comment]
heh funny how the idea always strikes me after I submit the comment :)
The issue appears if you pass already fetched data, not datasource.

try sth. like this
```php
$grid->setModel($this->model->findAll4Datagrid()->fetchAll());
// instead of this
$grid->setModel($this->model->findAll4Datagrid());
```

**Comment by Ciki** [comment]
@o5 have you had a chance to test it?

**Comment by o5** [comment]
Not yet, sorry. Coverage this bug in tests will be nice.
