### ISSUE TITLE
Sort replacement column "bug"

### ISSUE THREAD

**Issue by misaon** [o5/grido#249]
Mám dotaz,
když máš tabulky **domény** a **zákazníci**. U tabulky domény si vypisuji další informace jako např.: datum expirace, dostupnost... a mimo jiné i jméno zákazníka. To mám propojené s tabulkou zákazníci pomocí ID zákazníka. Potom v tabulce domén toto ID zákazníka přepisuji pomocí funkce **setReplacement**. Problém nastává v okamžiku filtraci a řazení. Stále se jména zákazníků v tabulce domén řadí podle onoho ID a ne podle přepsaného jména. Proto filtrace ani řazení nefungují "správně". Je nějaká jiná cesta jak tohle řešit?

**Comment by o5** [comment]
Pokud je to klasický join 1:1, tak si namapuj název sloupce/filtru na najoinovaný sloupec. V tvém případě něco jako:

SQL v modelu co nastavuješ Gridu.
```sql
SELECT d.*, z.jmeno as zakaznik
FROM domeny d
LEFT JOIN zakaznici z ON (d.zakaznik_id = z.id)
```

Definice sloupce
```php
$grid->addColumn('zakaznik', 'Zakaznik')
```
