### ISSUE TITLE
Sum of column

### ISSUE THREAD

**Issue by misaon** [o5/grido#250]
Zdravím,
už delší dobu se marně snažím dostat sumu určitého sloupce do samostatné proměnné a tu následně poslat do šablony, kde si ji vykreslím, je tohle možné?

Plánuješ v budoucnu do <tfoot> přidat možnost zobrazovat sumy sloupců?

Díky

**Comment by o5** [comment]
V blízké budoucnosti to v plánu nemám.
https://github.com/o5/grido/issues/57
