### ISSUE TITLE
Broken compatibility with PHP 5.3

### ISSUE THREAD

**Issue by k4reln** [o5/grido#251]
Hi,

in file src/Components/Export.php on line 86 (version 2.1.1) is used new array syntax []. This throw syntax error in PHP 5.3.*, but you have declared compatibility with PHP >5.3 in packagist.

Karel

**Comment by sasule** [comment]
In composer.json is in require section:  "php": ">=5.5", so I think PHP 5.3 compatibility is dead anyway.

**Comment by o5** [comment]
Should be fixed in **2.1.2**

**Comment by k4reln** [comment]
I know... But v2.1.2 has "php": ">=5.3" in composer.json and as you said, master has "php": ">=5.5". So which version is 100% compatible with PHP 5.3?

**Comment by o5** [comment]
@k4reln Only **v2.1.2**. 

Master never will be compatible with PHP 5.3. Please look at official PHP [Supported Versions](http://php.net/supported-versions.php) document. Current version (with security updates) is PHP 5.5.
