### ISSUE TITLE
Filter is not working without innerFilterControls

### ISSUE THREAD

**Issue by Olicek** [o5/grido#252]
I don't know if i do something wrong, but filter is not working until i uncomment [this part](https://github.com/o5/grido/blob/master/src/templates/bootstrap.latte#L68-L73). When i uncomment this piece of code it works properly (on click on the button or press Enter).

I have linked this js files in webloader (related to Grido):
```
- %wwwDir%/bower_components/nette.ajax.js/nette.ajax.js
- %wwwDir%/bower_components/typeahead.js/dist/bloodhound.min.js
- %wwwDir%/bower_components/typeahead.js/dist/typeahead.jquery.js
- %wwwDir%/bower_components/moment/min/moment.min.js
- %wwwDir%/bower_components/bootstrap-daterangepicker/daterangepicker.js
- %wwwDir%/bower_components/bootstrap-select/dist/js/bootstrap-select.min.js
- %wwwDir%/bower_components/grido/assets/dist/js/grido.bundle.js
```

Is it the right way how to use it uncomment it or copy it to my template?

**Comment by o5** [comment]
Thanks for reporting! It should be fixed soon
