### ISSUE TITLE
Grido has wrong size when bootstrap-select is open

### ISSUE THREAD

**Issue by Olicek** [o5/grido#254]
When bootstrap-select is open and grido has smaller height then select it use scrollbar to grido and cut bootstrap-select
![grido](https://cloud.githubusercontent.com/assets/2891953/12280240/aefea0fc-b98c-11e5-8da3-a7d724c6372c.png)

**Comment by o5** [comment]
This is probably issue of bootstrap's table responsible class. Do you know, how it should be fixed?

**Comment by Olicek** [comment]
You are right, it's bootstrap problem. It can be fixed with code below placed to .grido

```
&.table-responsive {
    overflow: visible;
}
```

Shall i prepare PR? You will want probably update sass and css files, right?

**Comment by o5** [comment]
You should modify only `.scss` and task runner will build css files. Pls, look into [Contributing file](https://github.com/o5/grido/blob/master/CONTRIBUTING.md#working-with-assets).
