### ISSUE TITLE
Malfunction auto filter when date range is set

### ISSUE THREAD

**Issue by Olicek** [o5/grido#255]
I set filter date range and use bootstrap template (i didn't try anything else), when i click on "Apply" in date range pickeru nothing happen. I have to go to another input and press enter.

**Comment by o5** [comment]
@Olicek Sorry for delay :/ Could you check it with latest version? You have to update also client-side. Thanks

**Comment by Olicek** [comment]
It's ok, i know it. I even tried repair it, but i'm not very good friend with js... :-)

It's working properly. Thanks. :+1:
