### ISSUE TITLE
Refresh table data via Ajax

### ISSUE THREAD

**Issue by misaon** [o5/grido#259]
Potřeboval bych data v tabulce obnovovat pomocí ajax požadavku v pravidelných intervalech. 
Použiji tedy handl, který zpracuji a pomocí grido->reload() vykreslím aktualizovanou tabulku. Problém je, že pokud jsem např. na třetí stránce (paginator), po provedení grido->reload() mě to šupne zpátky na tu první a zruší filtry. Ptám se tedy, existuje nějaký způsob, jak v tabulce obnovovat data při zachování filtrů?

**Comment by misaon** [comment]
Podařilo se mi to obejít pomocí $grid->setRememberState() , nevím ale, jestli je tento způsob řešení zcela ideální.

**Comment by o5** [comment]
Mělo by stačit, volat z JS handler [Grido::handleRefresh()](https://github.com/o5/grido/blob/bb1a50a7a3e22f1fba2c71a48fc0fdb5b05a545c/src/Grid.php#L718). Resetování dělá [Grido::handleReset()](https://github.com/o5/grido/blob/bb1a50a7a3e22f1fba2c71a48fc0fdb5b05a545c/src/Grid.php#L773-L783).

**Comment by misaon** [comment]
Počítám, že by to šlo i mnohem prostější metodou nemám-li pravdu:question: :smile:  
```
<script>
function autoRefreshLog() {
    var refreshHandleUrl = document.getElementById("frm-grid-form").getAttribute("data-grido-refresh-handler");
    $.nette.ajax({
        url: refreshHandleUrl
    });
}
setInterval(autoRefreshLog,10000);
</script>
```

**Comment by o5** [comment]
:+1:
