### ISSUE TITLE
Validate custom editControl

### ISSUE THREAD

**Issue by CZechBoY** [o5/grido#261]
Hi,
I'm missing custom edit control validation. Is it here or not?

```
$input = new TextInput;
$input->addRule(Form::INTEGER)
    ->addRule(Form::MAX, 'maximum 1234 overflow', 1234);

$grido->addColumnText(...)
    ->setEditableControl($input);
```

**Comment by sasule** [comment]
No idea wherer js validation exists or not (or any other). 
However, you can validate user-provided value when saving new data.  Then I think, you can return FALSE when data is not valid.

**Comment by o5** [comment]
Calling netteForms validation on edited cell should be easy done with small change of grido.js. For now, there is only server-side validation (hint has already posted by @sasule), but PR is welcome!
