### ISSUE TITLE
Is it working for Nette v2.3?

### ISSUE THREAD

**Issue by martinhofhanzl** [o5/grido#270]
I'm trying to install grido to my project, but it's not working. You can see in the picture below, what's written in composer after "composer require o5/grido". 
<img width="567" alt="snimek obrazovky 2016-04-08 v 7 36 56" src="https://cloud.githubusercontent.com/assets/9742529/14375000/cacd4540-fd5c-11e5-9246-7fde8bd3b703.png">

**Comment by o5** [comment]
You have to use dev-master for latest Nette.

**Comment by martinhofhanzl** [comment]
Can you please tell me how to do that? I added a few lines into composer.json, but it's still not working. How can I use dev-master?

**Comment by o5** [comment]
This line is from my `composer.json`.
```
"o5/grido": "dev-master",
```
