### ISSUE TITLE
translator support for replacement

### ISSUE THREAD

**Issue by Ciki** [o5/grido#272]
is there a way to set flag to translate all grido column replacements ?

```php
$grid->addColumnText('status', 'Status')
			->setReplacement($userStatuses) // not translated by default
			->setFilterSelect($userStatuses); // translated by default
```
If not, can it be added ([here](https://github.com/o5/grido/blob/master/src/Components/Columns/Column.php#L341) ? )

**Comment by o5** [comment]
Hmm, good catch!

In case of `->setFilterSelect()` it works thanks to nette's selectbox. I'm not sure, if the same behaviour would be for grido's `->setReplacement()`. Probably yes, but give me more time :)

**Comment by Ciki** [comment]
take your time ;)

2016-04-15 13:56 GMT+02:00 Petr Bugyík <notifications@github.com>:

> Hmm, good catch!
>
> In case of ->setFilterSelect() it works thanks to nette's selectbox. I'm
> not sure, if the same behaviour would be for grido's ->setReplacement().
> Probably yes, but give me more time :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/o5/grido/issues/272#issuecomment-210437332>
>



-- 
S pozdravom / Best Regards
Ing. Matúš Matula

**Comment by o5** [comment]
@Ciki: Could you check it please in your project? TX!

**Comment by Ciki** [comment]
@o5 it works, thanks!
