### ISSUE TITLE
Wrong initializing of the paginator

### ISSUE THREAD

**Issue by brosland** [o5/grido#275]
Hello,

I want to get data from a grid into a presenter. So I used method ```$grid->getData(FALSE)``` for that and it works fine. But if I want to render grid an error "Trying to get property of non-object" is thrown from grid's template. It is because you don't have initialized paginator correctly. The paginator should be set to template via getter ```$this->template->paginator = $this->getPaginator()```.

**Comment by o5** [comment]
Could you upload tracy error? The paginator should be [initialised properly](https://github.com/o5/grido/blob/master/src/Grid.php#L851).

**Comment by brosland** [comment]
I'm sorry, I have old version #908acc8. Someone set to composer ```"o5/grido": "dev-master#908acc8"``` in our project :-/.
