### ISSUE TITLE
client-side by bower not working properly?

### ISSUE THREAD

**Issue by JosefRypacek** [o5/grido#285]
**This issue has been modified.**

Hello,
grido (dev-master) installed by composer and client-side installed by bower is not working properly for me. Now I see that bower downloaded older files or some files are missing. I'll try it ASAP with assets from composer. Maybe following problems has been already fixed and I've just spent a lot of time with fixing already fixed code.

My original problems
-  click on item in typeahead don't refresh grid when filter is set to FILTER_OUTER (probably due to buttons bad location)
- paginator - manual enter of page (default / bootstrap) doesn't work (probably bad JS selector for default, but no idea what is wron with bootstrap version)
- buttons search and reset are weirdly located in bottom of grid (is is bug or very bad featrue?)

Thanks
Josef

**Comment by o5** [comment]
Hello @JosefRypacek, do you have also dev version of client-side package in your `bower.json`?

```json
 "grido": "git@github.com:o5/grido.git#611ae6b"
```

**Comment by JosefRypacek** [comment]
I had version "latest" which means old. I've updated to mentioned commit and Grido is working now :-). Thank you for your recommendation.
