### ISSUE TITLE
Document how to use setColumn

### ISSUE THREAD

**Issue by vrehak** [o5/grido#287]
The docs for setColumn says "namapuje na sloupec v db, lze použít callback". I was quite surprised that the following two codes perform behave differently:

```
$grid->addColumnDate('created', 'Created', \Grido\Components\Columns\Date::FORMAT_DATETIME)
           ->setColumn('o.created') 
           ->setDefaultSort(\Grido\Components\Columns\Column::ORDER_DESC)
            ->setSortable()
            ->setFilterDateRange();
```

(Attempt to read missing column 'o'.)

```
$grid->addColumnDate('created', 'Created', \Grido\Components\Columns\Date::FORMAT_DATETIME)
            ->setDefaultSort(\Grido\Components\Columns\Column::ORDER_DESC)
            ->setSortable()
            ->setFilterDateRange()
            ->setColumn('o.created');
```

(works as expected).

I guess this is intentional but it should be explained in the doc, IMHO,

**Comment by o5** [comment]
Hello @vrehak, thanks for issue. This is a standard behaviour when you use fluent api. Method `setFilterDateRange()` on column is only an alias for [$grid->addFilterDateRange()](https://github.com/o5/grido/blob/master/src/Components/Columns/Column.php#L389) and it is [already mentioned](https://github.com/o5/grido/blob/master/src/Components/Columns/Column.php#L385) in PHPDoc.
