### ISSUE TITLE
tree - subgrid(s)  

### ISSUE THREAD

**Issue by JStika** [o5/grido#305]
Chci se zaptat, jest-li se da grido\grid pouzit i pro stromove struktury jako subggrid(s), jak je videt u jineho gridu zde https://examples.planette.io/contributte/datagrid/tree-view?
V pripade, ze se da takto pouzit, pozadam o nakopnuti.

Dekuji za odpoved.

**Comment by Ciki** [comment]
@JStika myslim, ze toto v aktualnom stave nie je mozne

**Comment by JStika** [comment]
A mate nejakou radu, jak to resit?

**Comment by Ciki** [comment]
najjednoduchsie bude asi pouzit datagrid kt. spominate v 1. poste

**Comment by JStika** [comment]
Dekuji za odpoved.
Zel, tam prave neznenam zpusob jak data a tree zprovoznit a jak to "obleknout", aby to vypadalo jako grido [bootstrap 3]

**Comment by Ciki** [comment]
Chapem, pozrel by som si repo toho projektu https://github.com/contributte/datagrid a pripadne dotazy kladol tam. Zrejme tam bude example na subtree a mozno aj BS3 skin.. pripadne pohladat na nette foru

**Comment by JStika** [comment]
Dekuji za odpoved a Vasi ochotu.
Uz jsem vsechno "prosmejdil", zel bez vysledku, bez vetsiho poznani.
