### ISSUE TITLE
Možnost skrytí externích filtrů

### ISSUE THREAD

**Issue by pavelkouril** [o5/grido#94]
Občas je potřeba vypsat pouze data bez filtrování; nicméně v takovémto případě se objeví automaticky externí filtry, které nejdou skrýt.

Byla by možnost je natvrdo skrývat?

**Comment by o5** [comment]
Předělal jsem to, viz https://github.com/o5/grido/commit/a276fd838de8bf35b42fc92a3526261945f38c0c#commitcomment-15238688
